packages:
  - packages/*

catalog:
  jest: ^29.7.0
  rimraf: ^5.0.5
  supertest: ^6.3.4
  ts-jest: ^29.3.2
  ts-node: ^10.9.2
  turbo: ^1.12.2

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
