packages:
  - packages/*
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - nx
  - unrs-resolver
catalog:
  "@changesets/cli": ^2.29.2
  "@commitlint/cli": ^18.6.0
  "@commitlint/config-conventional": ^18.6.0
  "@contentful/rich-text-html-renderer": ^16.3.0
  "@contentful/rich-text-types": ^16.3.0
  "@ffmpeg/core": ^0.10.0
  "@ffmpeg/ffmpeg": ^0.10.1
  "@iarna/toml": ^2.2.5
  "@jungvonmatt/config-loader": ^0.6.0
  "@jungvonmatt/contentful-config": ^4.0.3
  "@jungvonmatt/contentful-ssg": ^4.0.3
  "@swc/core": ^1.3.104
  "@swc/jest": ^0.2.29
  "@types/dlv": ^1.1.4
  "@types/express": ^4.17.21
  "@types/fs-extra": ^11.0.4
  "@types/inquirer": ^9.0.7
  "@types/js-yaml": ^4.0.4
  "@types/listr": ^0.14.9
  "@types/micromatch": ^4.0.6
  "@types/node": ^20.11.5
  "@types/svgo": ^2.6.3
  "@typescript-eslint/parser": ^6.19.0
  casual: ^1.6.2
  cf-content-types-generator: ^2.16.0
  chalk: ^5.3.0
  change-case: ^5.4.2
  check-dependency-version-consistency: ^4.1.0
  cli-progress: ^3.9.1
  commander: ^11.1.0
  contentful: ^11.7.15
  contentful-management: ^11.54.4
  dlv: ^1.1.3
  esbuild: ^0.25.3
  eslint: ^8.56.0
  eslint-config-prettier: ^9.1.0
  eslint-config-xo: ^0.43.1
  eslint-config-xo-space: ^0.30.0
  eslint-config-xo-typescript: ^1.0.1
  eslint-import-resolver-typescript: ^3.6.1
  eslint-plugin-import: ^2.29.1
  exit-hook: ^4.0.0
  express: ^4.18.2
  find-cache-dir: ^5.0.0
  find-up: ^7.0.0
  get-port: ^7.0.0
  git-cz: ^4.9.0
  globby: ^14.0.0
  got: ^11.8.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  inquirer: ^12.9.3
  jest: ^29.7.0
  jest-esm-transformer: ^1.0.0
  jest-sonar: ^0.2.16
  jest-sonar-reporter: ^2.0.0
  js-yaml: ^4.1.0
  lerna: ^8.1.2
  lint-staged: ^15.5.1
  listr: ^0.14.3
  merge-options: ^3.0.4
  micromatch: ^4.0.5
  mkdirp: ^1.0.4
  node-homedir: ^2.0.0
  package-up: ^5.0.0
  pathe: ^2.0.3
  picocolors: ^1.0.0
  pirates: ^4.0.6
  pkg-dir: ^8.0.0
  randexp: ^0.5.3
  read-pkg-up: ^11.0.0
  rimraf: ^5.0.5
  rxjs: ^7.8.1
  semiver: ^1.1.0
  serialize-error: ^11.0.3
  serializr: ^3.0.2
  slash: ^5.1.0
  supertest: ^6.3.4
  svgo: ^2.8.0
  tar: ^7.4.3
  tempy: ^3.1.0
  ts-jest: ^29.3.2
  ts-morph: ^23.0.0
  ts-node: ^10.9.2
  turbo: ^1.12.2
  uuid: ^9.0.1
