import { getContentTypeId } from '../contentful.js';

/**
 * Get an ordered list of locales to use for translation based on fallback locales
 * @param {String} code Locale code
 * @param {Array} locales Array of contentful locale objects
 * @returns {Array} E.g. ['en-US', 'en-GB', 'de-DE']
 */
export const getLocaleList = (code, locales = []) => {
  const locale = locales.find((locale) => locale.code === code);
  return locale ? [locale.code, ...getLocaleList(locale.fallbackCode, locales)] : [];
};

/**
 * Try to get the localized value. Stops at the first valid locale in codes
 * @param {Object} field Object with values for different locales { 'de-DE': '...', 'en-US': '...' }
 * @param  {...any} codes Array with codes generated by getLocaleList
 */
export const localizeField = (field, ...codes) => {
  const [code, ...fallbackCodes] = codes;
  if (code && field.hasOwnProperty(code)) {
    return field[code];
  }

  if (fallbackCodes.length > 0) {
    return localizeField(field, ...fallbackCodes);
  }
};

/**
 * Localize fields from contentful entry
 * @param {Array} fields Contetful fields array
 * @param {String} code Locale code e.g. 'de-DE'
 * @param {Object} options Object containing locales & content types from contentful
 */
export const localizeEntry = (entry, code, options) => {
  const { locales, fieldSettings } = options;
  const { fields } = entry;
  const contentType = getContentTypeId(entry);
  // const { [getContentTypeId(entry)]: fieldSettings } = getFieldSettings(contentTypes) || {};
  const { [contentType]: settings } = fieldSettings;
  const { code: defaultCode } = locales.find((locale) => locale.default);
  const localeCodes = getLocaleList(code, locales);

  const isLocalized = (key) => settings?.[key]?.localized ?? false;

  return {
    ...entry,
    fields: Object.fromEntries(
      Object.entries(fields).map(([key, field]) =>
        isLocalized(key) ? [key, localizeField(field, ...localeCodes)] : [key, localizeField(field, defaultCode)]
      )
    ),
  };
};
